### ISSUE TITLE
Can't deploy code (source code violation)

### ISSUE THREAD

**Issue by Nainish-Rai** [aditya-shri/VPN#15]
Error Message : Can't deploy code as it violates salesforce policy

**Comment by Cordo-van-Saviour** [comment]
Same issue here

**Comment by aditya-shri** [comment]
Try forking and then deploying
OR
Download and deploy using Heroku-CLI

**Comment by aditya-shri** [comment]
Closing this issue as there's no other way to bypass Heroku ban, apart from what i have suggested.
