### ISSUE TITLE
Banned Dependency

### ISSUE THREAD

**Issue by steven2024** [aditya-shri/VPN#21]
![B0DFE1B5-9EC4-4944-A699-1BFCB0219D35](https://user-images.githubusercontent.com/89735533/195735040-135ce36d-5180-4b06-81e5-b27d09d1e2a2.jpeg)

**Comment by ilya12077** [comment]
Make your own fork of this project and delete readme.md and then deploy

**Comment by aditya-shri** [comment]
How did you deployed it?

**Comment by steven2024** [comment]
I got it to work on Heroku, I'll close this now.
