### ISSUE TITLE
[emerg] 24#24: invalid number of arguments in "listen" directive in /etc/nginx/conf.d/ss.conf:3

### ISSUE THREAD

**Issue by vickerson** [aditya-shri/VPN#35]
It seems there are some problems with your configuration files
![fail](https://github.com/aditya-shri/VPN/assets/125399944/7505d934-96ba-44c2-8496-e1799ffa163c)

**Comment by dzp1018** [comment]
您的邮件我已收到!     感谢您的来信，我会及时处理并回复。

**Comment by aditya-shri** [comment]
Is it failing vecause of this or is this just a warning?

**Comment by dzp1018** [comment]
您的邮件我已收到!     感谢您的来信，我会及时处理并回复。

**Comment by onebyoneby** [comment]
> 是因此而失败，还是这只是一个警告？

I also made this error when running dockerfile
