### ISSUE TITLE
Speed Issue

### ISSUE THREAD

**Issue by capriciousduck** [aditya-shri/VPN#9]
Hi. Thanks for your VPN. It's working great. However, the only issue I face is that the speed is slow. I get around 5Mbps even if my ISP offers 100Mbps. I kind of agree that with a VPN the speed is reduced but here, in this scenario, the speed is too slow. I would appreciate if you could help me.

**Comment by aditya-shri** [comment]
As you have said VPN is always kind off slow, same is the case here. Here the data is being passed through the heroku server each way. I can suggest other ways like changing DNS server, blocking 3rd party cookies etc to increase the speed. Other than these, I don't know any other way to increase speed unless you can increase speed of heroku server😅.

**Comment by aditya-shri** [comment]
I will be closing this issue. 
Please suggest if any other issue or feature you have in mind

**Comment by capriciousduck** [comment]
What encryption type do you recommend for good speed?

**Comment by capriciousduck** [comment]
And how do I block third-party cookies?

**Comment by capriciousduck** [comment]
Would changing proxy site variable increase the speed?

**Comment by aditya-shri** [comment]
Md-5, being the simplest, would help in increasing speed but it will reduce encryption of the vpn.

You can block 3rd party cookies in your browser settings. Just block it for all the websites and enable for only those which doesn't work correctly when encountered.

Changing proxy site will not help in increasing speed.

**Comment by capriciousduck** [comment]
Do you mean RC4-MD5?
